### ISSUE TITLE
typing_extensions.py is Missing "Any" Type

### ISSUE THREAD

**Issue by tbpassin** [Textualize/textual#2158]
Have you checked closed issues? https://github.com/Textualize/textual/issues?q=is%3Aissue+is%3Aclosed
yes

Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. **Check it can run without modifications.**

In v 0.16.0 from PyPi, the `Any` type is missing from _typimg_extensions_:

```
 File "C:\Users\tom\AppData\Roaming\Python\Python310\site-packages\textual\actions.py", line 6, in <module>
    from typing_extensions import Any, TypeAlias

ImportError: cannot import name 'Any' from 'typing_extensions' (C:\Users\tom\AppData\Local\Programs\Python\Python310\lib\site-packages\typing_extensions.py)
```
I got this exception when trying to run the demo program `hello_textual3.py`  (the first one I tried).

I added the type `Any` to the list of types in _typing_extensions.py_  and then the program ran correctly.

**Comment by willmcgugan** [comment]
What version of `typing_extensions` do you have?

Textual depends on 4.4.0 which does have Any.

**Comment by tbpassin** [comment]
I've got 4.5.0.  It must have been already installed, since some other packages use it, so perhaps it was upgraded today when I installed textual?

```
C:\Users\tom>py -m pip show typing-extensions
Name: typing_extensions
Version: 4.5.0
Summary: Backported and Experimental Type Hints for Python 3.7+
Home-page:
Author:
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
License:
Location: c:\users\tom\appdata\roaming\python\python310\site-packages
Requires:
Required-by: bokeh, mypy, panel, textual
```

Oh-oh, I hope none of those other Required-by programs don't break.  I'm running Python 3.10.9, BTW.

**Comment by willmcgugan** [comment]
It should work with `4.5.0`.  What happens if you do this from the REPL?

```python
>>> from typing_extensions import Any
```

**Comment by tbpassin** [comment]
Well, that's funny. I commented out the line I had added for 'Any'.  But the import attempt worked:
```
>>> from typing_extensions import Any
>>>
```

How could the import work in the REPL but not when textual tried the same import?

**Comment by willmcgugan** [comment]
Likely virtual environment related. Are you launching the REPL in a different way from running the Textual app?

**Comment by tbpassin** [comment]
No, I don't use venvs.  Hmm, I'll have to reconstruct how I ran textual the first time.

**Comment by TomJGooding** [comment]
> I got this exception when trying to run the demo program hello_textual3.py (the first one I tried).

Where did you find `hello_textual3.py`?

**Comment by tbpassin** [comment]
From [PythonLibrary](https://www.blog.pythonlibrary.org/2023/03/28/an-intro-to-textual/).  I thought that the demos were taken from the textual docs.  Sorry for referring to them so casually.

**Comment by tbpassin** [comment]
Now that I've reverted my change that added "Any" to typing_extensions.py, the demo program works as expected.  I can't figure out why it's working now and not before, but at least it's working.

I will close this issue now, and if the problem recurs I'll re-open it.  Thanks for responding so quickly.

**Comment by TomJGooding** [comment]
> From [PythonLibrary](https://www.blog.pythonlibrary.org/2023/03/28/an-intro-to-textual/). I thought that the demos were taken from the textual docs. Sorry for referring to them so casually.

Ah okay. I was curious as I couldn't find that anywhere in the Textual repo!

> I can't figure out why it's working now and not before, but at least it's working.

Glad it now seems to be working, but also glad I'm not having to struggle with Python on Windows any more! If you're not using virtual environments, I suspect different versions of Python installations could be the cause.

**Comment by tbpassin** [comment]
> If you're not using virtual environments, I suspect different versions of Python installations could be the cause

I don't think so since I always start Python with `py`, and I always run pip with `py -m pip` .  On more recent Windows installations, a `py.exe` program gets installed that always runs the most recent version unless you ask for another on the command line.  As long as I run consistently with `py`, all the pip installs go into the right place.

I suppose there could have been a problem with one version of a package getting installed into the sys location and another into the _--user_ location - not a problem unique to Windows, necessarily.   BTW, I don't use venvs as a rule because I have found that I forget what the different ones are for and what state they are in.  Instead, I tend to use a batch file to change the PYTHONPATH for whatever it is I'm working on.  This works pretty well.  Actually, I do the same on Linux.

**Comment by willmcgugan** [comment]
Suspect this was a local environment issue, the dependency in Textual is correct.

Closing for now. @tbpassin feel free to reopen if you identify a Textual issue.
