### ISSUE TITLE
rich.repr.ReprError when running in dev mode with CSS_PATH

### ISSUE THREAD

**Issue by 1j01** [Textualize/textual#2792]
Have you checked closed issues? Yes. This is a new issue, not present in a release yet.

When running an app that uses `CSS_PATH` with `textual run --dev`, the line
`self.log.system("STARTED", self.css_monitor)` is causing `rich.repr.ReprError: Failed to auto generate __rich_repr__; 'FileMonitor' object has no attribute 'paths'`

This was broken in #2744 when `paths` was changed to a private `_paths`.

```

 2023-06-16 20:39:30 ⌚  ironsmith in ~/Projects/textual/examples
± |detached:remotes/upstream/scroll-center-fix~5 {1} ✓| → textual run --dev code_browser.py
Traceback (most recent call last):
  File "/home/io/Projects/textual/examples/code_browser.py", line 77, in <module>
    CodeBrowser().run()
  File "/home/io/Projects/textual/src/textual/app.py", line 1205, in run
    asyncio.run(run_app())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/io/Projects/textual/src/textual/app.py", line 1194, in run_app
    await self.run_async(
  File "/home/io/Projects/textual/src/textual/app.py", line 1156, in run_async
    await app._process_messages(
  File "/home/io/Projects/textual/src/textual/app.py", line 1902, in _process_messages
    self.log.system("STARTED", self.css_monitor)
  File "/home/io/Projects/textual/src/textual/__init__.py", line 94, in __call__
    _log(
  File "/home/io/Projects/textual/src/textual/app.py", line 832, in _log
    self._handle_exception(error)
  File "/home/io/Projects/textual/src/textual/app.py", line 1820, in _handle_exception
    self._fatal_error()
  File "/home/io/Projects/textual/src/textual/app.py", line 1825, in _fatal_error
    traceback = Traceback(
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/traceback.py", line 264, in __init__
    trace = self.extract(
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/traceback.py", line 449, in extract
    locals={
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/traceback.py", line 450, in <dictcomp>
    key: pretty.traverse(
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/pretty.py", line 852, in traverse
    node = _traverse(_object, root=True)
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/pretty.py", line 837, in _traverse
    child_node = _traverse(child, depth=depth + 1)
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/pretty.py", line 647, in _traverse
    args = list(iter_rich_args(rich_repr_result))
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/pretty.py", line 614, in iter_rich_args
    for arg in rich_args:
  File "/home/io/.cache/pypoetry/virtualenvs/textual-iEkC3TU5-py3.10/lib/python3.10/site-packages/rich/repr.py", line 84, in auto_rich_repr
    raise ReprError(
rich.repr.ReprError: Failed to auto generate __rich_repr__; 'FileMonitor' object has no attribute 'paths'
```
